// Publishing-Tracker/src/publishing-tracker-ui/src/components/MainLayout.tsx
import React from 'react';
import { Outlet, Link } from 'react-router-dom';
import ProtectedRoute from './ProtectedRoute';

const MainLayout = () => {
    return (
        <ProtectedRoute>
            <div className="main-layout">
                <nav>
                    <ul>
                        <li><Link to="/dashboard">Dashboard</Link></li>
                        <li><Link to="/books">Books</Link></li>
                        <li><Link to="/sales">Sales</Link></li>
                        <li><Link to="/import">Import</Link></li>
                        <li><Link to="/platforms">Platforms</Link></li>
                    </ul>
                </nav>
                <main>
                    <Outlet />
                </main>
            </div>
        </ProtectedRoute>
    );
};

export default MainLayout;

// Publishing-Tracker/ng_ver/publishing-tracker-ui-angular/src/app/shared/components/main-layout/main-layout.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-main-layout',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './main-layout.component.html',
  styleUrls: ['./main-layout.component.css']
})
export class MainLayoutComponent { }
<div class="main-layout">
  <nav>
    <ul>
      <li><a routerLink="/dashboard">Dashboard</a></li>
      <li><a routerLink="/books">Books</a></li>
      <li><a routerLink="/sales">Sales</a></li>
      <li><a routerLink="/import">Import</a></li>
      <li><a routerLink="/platforms">Platforms</a></li>
    </ul>
  </nav>
  <main>
    <router-outlet></router-outlet>
  </main>
</div>
